create table pc_status (
    id bigint generated by default as identity primary key,
    hostname text,
    cpu_usage double precision,
    ram_usage double precision,
    disk_usage double precision,
    created_at timestamp with time zone default now()
);
